// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZZyiAbeeeyIrxy3t5Y38pg_Fg3xOEG0',
    appId: '1:18505588509:web:3e6177905d5fe3f11ecbf4',
    messagingSenderId: '18505588509',
    projectId: 'a-check-3c3c8',
    authDomain: 'a-check-3c3c8.firebaseapp.com',
    storageBucket: 'a-check-3c3c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv9gt5UIEA0IZfFWpYLNqn72sVOl-mOAE',
    appId: '1:18505588509:android:50f4de0fa4f4af231ecbf4',
    messagingSenderId: '18505588509',
    projectId: 'a-check-3c3c8',
    storageBucket: 'a-check-3c3c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiNdGKpe2VjL8F4DtEETY1Ch4NQR1xy00',
    appId: '1:18505588509:ios:ee8d108d42d328b11ecbf4',
    messagingSenderId: '18505588509',
    projectId: 'a-check-3c3c8',
    storageBucket: 'a-check-3c3c8.appspot.com',
    iosClientId: '18505588509-v1t2q77q9nvcvhljo926bimpdi4f01r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.aCheckProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiNdGKpe2VjL8F4DtEETY1Ch4NQR1xy00',
    appId: '1:18505588509:ios:ee8d108d42d328b11ecbf4',
    messagingSenderId: '18505588509',
    projectId: 'a-check-3c3c8',
    storageBucket: 'a-check-3c3c8.appspot.com',
    iosClientId: '18505588509-v1t2q77q9nvcvhljo926bimpdi4f01r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.aCheckProject',
  );
}
